---
platform: windows

inputs:
- name: ci
- name: repo

run:
  path: powershell
  args: 
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/docker-test-rootfs/run.ps1

params:
  DOCKERFILE: ""
  IMAGE_NAME: ""
  OS_VERSION: ""
  EPHEMERAL_DISK_TEMP_PATH: ''
  SHARE_IP: ''
  SHARE_FQDN: ''
  SHARE_NAME: ''
  SHARE_USERNAME: ''
  SHARE_PASSWORD: ''
